services:
  bundle_server:
    url: http://bundle-server
  collector:
    url: http://collector:8081

bundles:
  identity:
    service: bundle_server
    resource: bundle.tar.gz
    polling:
      min_delay_seconds: 1
      max_delay_seconds: 2

decision_logs:
  service: collector
  resource: /
  reporting:
    min_delay_seconds: 1
    max_delay_seconds: 2
